-- =========================================================
-- ISSUE 8
-- PRODUCTOS NUEVOS DENTRO DE UNA SOLICITUD
-- =========================================================

CREATE TABLE IF NOT EXISTS solicitud_productos_nuevos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  solicitud_id INTEGER NOT NULL,

  nombre VARCHAR(150) NOT NULL,
  descripcion TEXT NOT NULL,
  categoria_id INTEGER NOT NULL,

  cantidad_solicitada NUMERIC(12,2) NOT NULL
    CHECK (cantidad_solicitada > 0),

  proveedor_sugerido VARCHAR(150),
  proveedor_link TEXT,
  sku_sugerido VARCHAR(100),

  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_producto_nuevo_solicitud
    FOREIGN KEY (solicitud_id)
    REFERENCES solicitudes(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_producto_nuevo_categoria
    FOREIGN KEY (categoria_id)
    REFERENCES categorias(id)
);

CREATE INDEX IF NOT EXISTS idx_producto_nuevo_solicitud
  ON solicitud_productos_nuevos(solicitud_id);

CREATE INDEX IF NOT EXISTS idx_producto_nuevo_categoria
  ON solicitud_productos_nuevos(categoria_id);