-- =========================================================
-- INVENTARIO ENIGMA ROOMS
-- Esquema PostgreSQL
-- =========================================================


-- =========================================================
-- 1. CATEGORIAS
-- =========================================================

CREATE TABLE categorias (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  descripcion VARCHAR(255),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 2. UBICACIONES
-- =========================================================

CREATE TABLE ubicaciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,

  tipo VARCHAR(30) NOT NULL
    CHECK (
      tipo IN (
        'central',
        'sucursal',
        'equipo_interno'
      )
    ),

  puede_solicitar_a_nombre_de_otra BOOLEAN NOT NULL DEFAULT FALSE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 3. USUARIOS
-- =========================================================

CREATE TABLE usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  email VARCHAR(150) UNIQUE,
  password_hash VARCHAR(255),
  pin_hash VARCHAR(255),

  rol VARCHAR(30) NOT NULL
    CHECK (
      rol IN (
        'principal',
        'sucursal',
        'equipo_interno'
      )
    ),

  nivel_permiso VARCHAR(30)
    CHECK (
      nivel_permiso IS NULL
      OR nivel_permiso IN (
        'consulta',
        'operador',
        'aprobador_admin'
      )
    ),

  ubicacion_id INTEGER NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_usuario_ubicacion
    FOREIGN KEY (ubicacion_id)
    REFERENCES ubicaciones(id)
);


-- =========================================================
-- 4. PRODUCTOS
-- =========================================================

CREATE TABLE productos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  descripcion TEXT,
  sku VARCHAR(100) NOT NULL UNIQUE,
  categoria_id INTEGER,
  unidad_medida VARCHAR(50) NOT NULL,
  punto_reorden NUMERIC(12,2) NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_producto_categoria
    FOREIGN KEY (categoria_id)
    REFERENCES categorias(id)
);


-- =========================================================
-- 5. INVENTARIO
-- =========================================================

CREATE TABLE inventario (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ubicacion_id INTEGER NOT NULL,
  producto_id INTEGER NOT NULL,
  cantidad NUMERIC(12,2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT uk_inventario_ubicacion_producto
    UNIQUE (ubicacion_id, producto_id),

  CONSTRAINT fk_inventario_ubicacion
    FOREIGN KEY (ubicacion_id)
    REFERENCES ubicaciones(id),

  CONSTRAINT fk_inventario_producto
    FOREIGN KEY (producto_id)
    REFERENCES productos(id)
);


-- =========================================================
-- 6. PROVEEDORES
-- =========================================================

CREATE TABLE proveedores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  contacto VARCHAR(150),
  telefono VARCHAR(30),
  email VARCHAR(150),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 7. PRODUCTOS POR PROVEEDOR
-- =========================================================

CREATE TABLE proveedor_productos (
  proveedor_id INTEGER NOT NULL,
  producto_id INTEGER NOT NULL,

  PRIMARY KEY (
    proveedor_id,
    producto_id
  ),

  CONSTRAINT fk_proveedor_producto_proveedor
    FOREIGN KEY (proveedor_id)
    REFERENCES proveedores(id),

  CONSTRAINT fk_proveedor_producto_producto
    FOREIGN KEY (producto_id)
    REFERENCES productos(id)
);


-- =========================================================
-- 8. SOLICITUDES
-- =========================================================

CREATE TABLE solicitudes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  destino_ubicacion_id INTEGER NOT NULL,
  creado_por_usuario_id INTEGER NOT NULL,
  solicitante_ubicacion_id INTEGER NOT NULL,

  estado VARCHAR(30) NOT NULL DEFAULT 'solicitada'
    CHECK (
      estado IN (
        'solicitada',
        'en_revision',
        'aprobada',
        'en_transito',
        'recibida',
        'cerrada',
        'rechazada'
      )
    ),

  motivo_cierre TEXT,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_solicitud_destino
    FOREIGN KEY (destino_ubicacion_id)
    REFERENCES ubicaciones(id),

  CONSTRAINT fk_solicitud_usuario
    FOREIGN KEY (creado_por_usuario_id)
    REFERENCES usuarios(id),

  CONSTRAINT fk_solicitud_solicitante
    FOREIGN KEY (solicitante_ubicacion_id)
    REFERENCES ubicaciones(id)
);


-- =========================================================
-- 9. LINEAS DE SOLICITUD
-- =========================================================

CREATE TABLE solicitud_lineas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  solicitud_id INTEGER NOT NULL,
  producto_id INTEGER NOT NULL,

  cantidad_solicitada NUMERIC(12,2) NOT NULL,
  cantidad_aprobada NUMERIC(12,2) DEFAULT 0,
  cantidad_enviada_acumulada NUMERIC(12,2) NOT NULL DEFAULT 0,
  cantidad_recibida_acumulada NUMERIC(12,2) NOT NULL DEFAULT 0,

  CONSTRAINT fk_solicitud_linea_solicitud
    FOREIGN KEY (solicitud_id)
    REFERENCES solicitudes(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_solicitud_linea_producto
    FOREIGN KEY (producto_id)
    REFERENCES productos(id)
);


-- =========================================================
-- 10. ENVIOS
-- =========================================================

CREATE TABLE envios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  solicitud_id INTEGER NOT NULL,

  estado VARCHAR(30) NOT NULL DEFAULT 'preparacion'
    CHECK (
      estado IN (
        'preparacion',
        'en_transito',
        'recibido',
        'cancelado'
      )
    ),

  creado_por_usuario_id INTEGER NOT NULL,
  confirmado_por_usuario_id INTEGER,

  fecha_envio TIMESTAMP,
  fecha_recepcion TIMESTAMP,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_envio_solicitud
    FOREIGN KEY (solicitud_id)
    REFERENCES solicitudes(id),

  CONSTRAINT fk_envio_creado_por
    FOREIGN KEY (creado_por_usuario_id)
    REFERENCES usuarios(id),

  CONSTRAINT fk_envio_confirmado_por
    FOREIGN KEY (confirmado_por_usuario_id)
    REFERENCES usuarios(id)
);


-- =========================================================
-- 11. LINEAS DE ENVIO
-- =========================================================

CREATE TABLE envio_lineas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  envio_id INTEGER NOT NULL,
  solicitud_linea_id INTEGER NOT NULL,

  cantidad_enviada NUMERIC(12,2) NOT NULL,

  CONSTRAINT fk_envio_linea_envio
    FOREIGN KEY (envio_id)
    REFERENCES envios(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_envio_linea_solicitud_linea
    FOREIGN KEY (solicitud_linea_id)
    REFERENCES solicitud_lineas(id)
);


-- =========================================================
-- 12. MOVIMIENTOS
-- =========================================================

CREATE TABLE movimientos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ubicacion_id INTEGER NOT NULL,
  producto_id INTEGER NOT NULL,
  usuario_id INTEGER NOT NULL,

  tipo VARCHAR(30) NOT NULL
    CHECK (
      tipo IN (
        'entrada',
        'salida',
        'transferencia_salida',
        'transferencia_entrada',
        'ajuste_positivo',
        'ajuste_negativo',
        'merma',
        'consumo'
      )
    ),

  cantidad NUMERIC(12,2) NOT NULL,

  referencia_tipo VARCHAR(50),
  referencia_id INTEGER,
  motivo TEXT,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_movimiento_ubicacion
    FOREIGN KEY (ubicacion_id)
    REFERENCES ubicaciones(id),

  CONSTRAINT fk_movimiento_producto
    FOREIGN KEY (producto_id)
    REFERENCES productos(id),

  CONSTRAINT fk_movimiento_usuario
    FOREIGN KEY (usuario_id)
    REFERENCES usuarios(id)
);


-- =========================================================
-- 13. ORDENES DE COMPRA
-- =========================================================

CREATE TABLE ordenes_compra (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  proveedor_id INTEGER NOT NULL,
  creado_por_usuario_id INTEGER NOT NULL,

  estado VARCHAR(30) NOT NULL DEFAULT 'borrador'
    CHECK (
      estado IN (
        'borrador',
        'enviada',
        'parcial',
        'recibida',
        'cancelada'
      )
    ),

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_orden_proveedor
    FOREIGN KEY (proveedor_id)
    REFERENCES proveedores(id),

  CONSTRAINT fk_orden_usuario
    FOREIGN KEY (creado_por_usuario_id)
    REFERENCES usuarios(id)
);


-- =========================================================
-- 14. LINEAS DE ORDEN DE COMPRA
-- =========================================================

CREATE TABLE orden_compra_lineas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  orden_compra_id INTEGER NOT NULL,
  producto_id INTEGER NOT NULL,

  cantidad_solicitada NUMERIC(12,2) NOT NULL,
  cantidad_recibida NUMERIC(12,2) NOT NULL DEFAULT 0,
  costo_unitario NUMERIC(12,2),

  CONSTRAINT fk_orden_linea_orden
    FOREIGN KEY (orden_compra_id)
    REFERENCES ordenes_compra(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_orden_linea_producto
    FOREIGN KEY (producto_id)
    REFERENCES productos(id)
);